version: '2.4'

# Docker Compose for Github CI setup
#   This file builds the shr image from source
services:
  shr:
    container_name: shr
    image: test-image:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
    volumes:
      - ./config/config_ci.json:/app/config/config_docker.json
      - ./config/mediator.json:/app/config/mediator.json

  shr-fhir:
    image: hapiproject/hapi:latest
    hostname: shr-fhir
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - hapi-data:/data/hapi
  
  ###
  # OpenHIM
  ###
  openhim-core:
    image: jembi/openhim-core:latest
    hostname: openhim-core
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    ports:
      - 8080:8080
      - 5000:5000
      - 5001:5001
    healthcheck:
      test: "curl -sSk https://localhost:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

volumes:
  mongo-data:
  hapi-data: