version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

## Utility for booting up placeholder page:
# `docker run --hostname openhim-placeholder --network shared-health-record_sedish --name openhim-placeholder -e MESSAGE=OPENHIM-PLACEHOLDER -e PORT=3000 -d docker.io/sroze/landing-page:latest`

services:
  shr:
    build: ./
    container_name: shr
    hostname: shr
    ports:
      3000:3000
    environment:
      - NODE_ENV=docker
    volumes:
      - ./config/config_docker.json:/app/config/config_docker.json
      - ./config/mediator.json:/app/config/mediator.json

  shr-fhir:
    image: hapiproject/hapi:latest
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - hapi-data:/data/hapi
  
  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    ports:
      - 8080:8080
      - 5000:5000
      - 5001:5001
    healthcheck:
      test: "curl -sSk https://localhost:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    ports:
      - "80:80"
    #volumes:
      # - ./configs/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://localhost || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  mongo-db:
    container_name: mongo-db
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

volumes:
  mongo-data:
  hapi-data: