version: '2.4'

# Docker Compose for Github CI setup
services:
  shr:
    container_name: shr
    hostname: shr
    image: test-image:latest
    environment:
      - NODE_ENV=docker
    ports:
      - 3001:3001
    volumes:
      - ./config/config_ci.json:/app/config/config_docker.json
      - ./config/mediator_ci.json:/app/config/mediator_docker.json

  shr-fhir:
    image: hapiproject/hapi:latest
    hostname: shr-fhir
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - hapi-data:/data/hapi
  
  ###
  # OpenHIM
  ###
  openhim-core:
    image: jembi/openhim-core:latest
    hostname: openhim-core
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    ports:
      - 8080:8080
      - 5000:5000
      - 5001:5001
    healthcheck:
      test: "curl -sSk https://localhost:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
  mongo-db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  # OpenHIM Config
  openhim-config:
    container_name: openhim-config
    image: ghcr.io/i-tech-uw/openhim-config:latest
    volumes:
      - ./config/openhim/ci-openhim-config.json:/app/test-openhim-config.json

  # Newman Tests
  newman:
    image: postman/newman
    environment: 
      - $POSTMAN_COLLECTION
    volumes:
      - ./.postman:/.postman
    entrypoint: newman run $POSTMAN_COLLECTION -e /.postman/ci.postman_environment.json --insecure --timeout-request 10000 --delay-request 10000
  
  # MLLP Tests
  mllp_tests:
    container_name: mllp_tests
    image: ghcr.io/b-techbw/mllp-tester:main
    volumes:
      - ./test/mllp:/test

  # Task Runner
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper

  # Not necessary
  openhim-console:
    image: jembi/openhim-console:latest
    restart: unless-stopped
    ports:
      - "80:80"
    #volumes:
      # - ./configs/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://localhost || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
  
volumes:
  mongo-data:
  hapi-data:
  kafka-data:
