version: '3.8'

## Container debugging:
# 1. append the following lines to desired container
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
#
#    tty: true
#    stdin_open: true
#    entrypoint: bash


# Building: docker build ./ --build-arg NODE_AUTH_TOKEN -t ghcr.io/i-tech-uw/shared-health-record:local

services:
  # shr: Run natively using yarn, or see docker-compose.yml
  shr:
    container_name: shr
    restart: unless-stopped
    hostname: shr
    image: itechuw/shared-health-record:dev
    build:
      context: ./
      args:
        - NODE_ENV=docker
    ports:
      - 4000:3000
      - 3001:3001
      - 3002:3001
      - '9230:9230'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=docker
    volumes:
      - ./config/config_docker.json:/app/config/config_docker.json
      - ./config/mediator_docker.json:/app/config/mediator_docker.json
    entrypoint: node --inspect=0.0.0.0:9230 /app/dist/app.js
    # tty: true
    # stdin_open: true
    # entrypoint: bash
    networks:
      - hie
networks:
  hie:
    external: true
    name: hie-botswana_hie
