version: '3.9'

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  # shr: Run natively using yarn, or see docker-compose.yml
  shr:
    container_name: shr
    hostname: shr
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
    volumes:
      - ./config/config_development.json:/app/config/config_docker.json
      - ./config/mediator_development.json:/app/config/mediator_docker.json
    networks:
      - hie
    profiles: ["shr"]
    
  shr-fhir:
    container_name: shr-fhir
    hostname: shr-fhir
    image: hapiproject/hapi:latest
    restart: unless-stopped
    volumes:
      - hapi-data:/data/hapi
    networks:
      - hie
    profiles: ["dev"]
    ports:
      - 8090:8080

  # Kafka Task Runners
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - /bitnami/kafka
networks:
  hie:
    external: true
    name: hie-botswana_hie