name: Run API Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  newman-test:
    timeout-minutes: 10
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build SHR
      run: docker-compose -f ci.docker-compose.yml build shr  
    
    - name: Start containers
      run: docker-compose -f ci.docker-compose.yml up -d

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Show containers
      run: docker-compose -f "ci.docker-compose.yml" ps

    - uses: matt-ball/newman-action@master
      with:
        collection: https://www.getpostman.com/collections/481bb6cc8e1e964fd8bd # FHIR Metadata
        environment: .postman/github.postman_environment.json

    - name: Stop containers
      if: always()
      run: docker-compose -f "dev.docker-compose.yml" down