name: Run API Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  newman-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build SHR
        uses: docker/build-push-action@v2
        with:
          tags: test-image:latest
          push: false
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start containers
        run: docker-compose -f ci.docker-compose.yml up -d

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Show containers
        run: docker-compose -f "ci.docker-compose.yml" ps

      - name: Show SHR Log
        run: docker-compose -f "ci.docker-compose.yml" logs -f shr

      - uses: matt-ball/newman-action@master
        with:
          collection: https://www.getpostman.com/collections/481bb6cc8e1e964fd8bd # FHIR Metadata
          environment: .postman/github.postman_environment.json

      - name: Stop containers
        if: always()
        run: docker-compose -f "dev.docker-compose.yml" down
